/********************************************************************************
  server.js
    Application client server.  Serves the build folder generated by Gulp on your machine's specified port.  After starting the server, you can access the application in your browser at:
      http://localhost:[PORT]
    where "[PORT]" is replaced with the integer value of the "PORT" variable declared below.
********************************************************************************/

'use strict';

// Native Node Modules
const path = require('path');

// NPM Modules
const express = require('express');
const server = express();

// Local Variables
const PORT = 5000;

// Start the Express server and statically serve the build folder in this project's root directory.
server.use(express.static(path.join(__dirname, 'build')));
server.listen(PORT, () => console.log(`Application client server running on port ${PORT}.`));
